#aca voy a separar la columna de la tabla de datacsv a mas tablas dentro de datavisas
DROP DATABASE IF EXISTS Visash1;
CREATE DATABASE Visash1;
USE Visash1;
DROP TABLE IF EXISTS CaseInfo;
CREATE TABLE CaseInfo (
  CASE_NUMBER INTEGER UNIQUE NOT NULL,
  Case_STATUS VARCHAR(10) NOT NULL,
  YEAR VARCHAR (4) NOT NULL,
PRIMARY KEY(CASE_NUMBER)
); 

DROP TABLE IF EXISTS JobDescrip;
CREATE TABLE JobDescrip (
  CASE_NUMBER INTEGER NOT NULL,
  FULL_TIME_POSITION VARCHAR(1),
  JOB_TITLE VARCHAR(30) NOT NULL,
  PREVAILING_WAGE FLOAT NOT NULL,
  WORKSITE_STATE_ABB VARCHAR(10) NOT NULL,
 PRIMARY KEY(PREVAILING_WAGE),
 FOREIGN KEY(CASE_NUMBER) REFERENCES CaseInfo (CASE_NUMBER)
);


DROP TABLE IF EXISTS SocName;
CREATE TABLE SocName (
  CASE_NUMBER INTEGER NOT NULL,
  SOC_NAME VARCHAR(15) NOT NULL,
  EMPLOYER_NAME VARCHAR(15) NOT NULL,
  FOREIGN KEY(CASE_NUMBER) REFERENCES CaseInfo (CASE_NUMBER),
  PRIMARY KEY(EMPLOYER_NAME) #no esta bueno que el PK sea un nombre pero elimine el codigo de la compania 
);



LOAD DATA LOCAL INFILE 
' /Users/florenciaross/Desktop/H1_Visas.csv' 
INTO TABLE CaseInfo 
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n' 
IGNORE 1 ROWS (CASE_NUMBER, CASE_STATUS, YEAR) ;
#para importar los datos del csv a la base de datos 


